kind: pipeline
name: default

steps:
- name: build
  image: golang
  commands:
    - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o cloudflare-workers

- name: docker  
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_hub_user
    password: 
      from_secret: docker_hub_password
    repo: digitalwerber/cloudflare-workers-drone-plugin
    tags: latest