kind: pipeline
name: default

steps:
- name: build
  image: golang
<<<<<<< HEAD
  environment:
    GOOS: linux
    GOARCH: amd64
    CGO_ENABLED: 0
  commands:
    - go get -u github.com/pkg/errors
    - go get -u github.com/iancoleman/strcase
    - go build -o cloudflare-workers
=======
  commands:
    - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o cloudflare-workers
>>>>>>> master

- name: docker  
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_hub_user
    password: 
      from_secret: docker_hub_password
    repo: digitalwerber/cloudflare-workers-drone-plugin
    tags: latest